name: "Dev Deploy-bak"

on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**/*.png'
  workflow_dispatch:

jobs:
  build-jar:
    name: Build Jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew boot:bootJar party.memshell.news:build

      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: memshell-party-boot-jar
          path: boot/build/libs/boot-*.jar

      - name: Upload Web
        uses: actions/upload-artifact@v4
        with:
          name: memshell-party-web
          path: party.memshell.news/build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-jar
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Jar
        uses: actions/download-artifact@v4
        with:
          name: memshell-party-boot-jar
          path: boot/build/libs

      - name: Download Web
        uses: actions/download-artifact@v4
        with:
          name: memshell-party-web
          path: party.memshell.news/build

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
          script: |
            cd /opt/memshell-party
            # Stop the old service
            if systemctl is-active --quiet memshell-party.service; then
              sudo systemctl stop memshell-party.service
            fi
            # Backup old jar
            if [ -f "boot/build/libs/boot-*.jar" ]; then
              mv boot/build/libs/boot-*.jar boot/build/libs/boot-*.jar.bak
            fi
            # Backup old web
            if [ -d "party.memshell.news/build" ]; then
              mv party.memshell.news/build party.memshell.news/build.bak
            fi
            # Move new jar
            mv /tmp/memshell-party-boot-jar/boot-*.jar boot/build/libs/
            # Move new web
            mv /tmp/memshell-party-web party.memshell.news/
            # Start the new service
            sudo systemctl start memshell-party.service
            sudo systemctl status memshell-party.service

