name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  info:
    name: Parse Release Info
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      version-without-v: ${{ steps.get_version.outputs.version-without-v }}
      changelog: ${{ steps.get_changelog.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION_WITHOUT_V=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version-without-v=$VERSION_WITHOUT_V" >> $GITHUB_OUTPUT

      - name: Get ChangeLog
        id: get_changelog
        uses: appleboy/changelog-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: CHANGELOG.md
          version: ${{ steps.get_version.outputs.version }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: info
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew boot:bootJar

      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: memshell-party-boot-jar
          path: boot/build/libs/boot-*.jar

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [info, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Jar
        uses: actions/download-artifact@v4
        with:
          name: memshell-party-boot-jar
          path: boot/build/libs

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.info.outputs.version }}
          name: Release ${{ needs.info.outputs.version }}
          body: ${{ needs.info.outputs.changelog }}
          draft: false
          prerelease: false
          files: boot/build/libs/boot-*.jar

      - name: Publish to Maven Central
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

